### ISSUE TITLE
App Inventor Grote Rode Knop

### ISSUE THREAD

**Issue by ghost** [CoderDojo-Content/Community#91]
Dutch translation of Big Red Button Sushi Card App Inventor

**Comment by ghost** [comment]
[app-inventor-grote-rode-knop-nl.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5f02aae5869a00115fa68b/125516c66e82c728ace21e0d46e9848a6e8b8dbf8ae7ab4cb610f7862652223e3b0ba72e3d8eed27af0f750d4d435cec03070511afbd9b21b4b33523db5e58bb873c5b7c973b45acb8834de950e828834797aaaec81d9ebc6278bec1da0d2c14171981f55c30a19f4acf5ef348e34952a3017b.pdf)

**Comment by ghost** [comment]
Summary: Ninja's maken een simpele app voor Android apparaten (of voeren het uit via een lokale emulator).

**Comment by CiaraMcHugh** [comment]
https://forums.coderdojo.com/topic/573/dutch-app-inventor-resources
